In [1]:
import numpy as np

In [24]:
X = np.arange(1,7).reshape(3,2)
w = np.arange(1,3).reshape(2,1)
y = np.arange(1,4).reshape(3,1)
D = 2
N = 3

In [3]:
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
y

array([[1],
       [2],
       [3]])

In [5]:
w

array([[1],
       [2]])

In [8]:
A = 2 * np.sum(X**2, axis=0).reshape(D,1)
C = 2 * np.sum(X * (y - X @ w), axis=0).reshape(D,1) + w * A

In [19]:
A

array([[ 70],
       [112]])

In [14]:
C

array([[-132],
       [ -32]])

In [15]:
C_new = np.zeros((2,1))

In [17]:
for j in range(D):
    for i in range(N):
        C_new[j,0] += 2 * X[i,j] * (y[i,0] - X[i:i+1] @ w + w[j,0] * X[i,j])

In [18]:
C

array([[-132],
       [ -32]])

In [25]:
XX[:,:] = X[:,:]

In [26]:
XX

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
X[0,0] = 10

In [28]:
XX

array([[1, 2],
       [3, 4],
       [5, 6]])